### ISSUE TITLE
Installing specific version of chromedriver

### ISSUE THREAD

**Issue by nneal** [flavorjones/chromedriver-helper#24]
I need to install a specific version of chromedriver, specifically `2.2.0` for use on CircleCI in my rspec test setup. Is there a way to configure this through this gem, or should I be looking elsewhere?

**Comment by ramyavi** [comment]
Hi Any updates on this please as i need to do the same on the circle CI ? Thanks

**Comment by nneal** [comment]
@ramyavi we ended up just using default selenium / webkit. Couldn't find a good solution on our own to use chromedriver

**Comment by sodacode** [comment]
Bit of a hack as I don't have much time to work on it, but I made a fork where you can `export CHROMEDRIVER_VERSION = 'x.xx'` and run `chromedriver-update` to get the specific version you want. https://github.com/Leanstack/chromedriver-helper

**Comment by jonny5** [comment]
I opened a pull request to add versioning to the gem because I was running into the same issue: https://github.com/flavorjones/chromedriver-helper/pull/34

**Comment by flavorjones** [comment]
Closing this, as I'm looking at merging PR #34 now.
