### ISSUE TITLE
CentOS 6.6 support: download libstdc++

### ISSUE THREAD

**Issue by Vanuan** [flavorjones/chromedriver-helper#25]
Currently it only downloads chromedriver binary. It doesn't work on CentOS 6.6 as is. We need to download newer libstdc++ add a proxy script that sets LD_LIBRARY_PATH.
Here's how it's done in Chrome:
http://chrome.richardlloyd.org.uk/

**Comment by Vanuan** [comment]
https://github.com/twKrash/chromedriver-helper/commit/af23885e53adf8101cfcf2b64e433629f60bdee1

**Comment by flavorjones** [comment]
Investigating.

**Comment by flavorjones** [comment]
The error message I'm seeing, which I imagine is what you saw and what caused you to open this issue, is:

```
/home/vagrant/.chromedriver-helper/linux64/chromedriver: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/vagrant/.chromedriver-helper/linux64/chromedriver)
/home/vagrant/.chromedriver-helper/linux64/chromedriver: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /home/vagrant/.chromedriver-helper/linux64/chromedriver)
/home/vagrant/.chromedriver-helper/linux64/chromedriver: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/vagrant/.chromedriver-helper/linux64/chromedriver)
```

**Comment by flavorjones** [comment]
I've opted to to document how a user of `chromedriver` can make sure libraries are present and loaded.

I feel strongly that it's not the job of chromedriver-helper to work around this kind of compatibility issue. However, I would like to make sure users are happy. Please check out the README and let me know if you think it's not sufficient.
