### ISSUE TITLE
Old chromedriver binary returns EOFError

### ISSUE THREAD

**Issue by lindayang** [flavorjones/chromedriver-helper#37]
After installing chromedriver helper, I see: 

```
.rvm/gems/ruby-2.3.0/bin/chromedriver -v
ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4)
```

When I try to load it from my code, it returns an EOFError. Manually upgrading the chromedriver binary to ChromeDriver 2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1) fixed the problem. 

Can we update chromedriver-helper to use latest binary?

**Comment by twKrash** [comment]
As far as I know chomedriver-helper tries to download the latest chromedriver from google. But I've found that it is not. Didn't have chance to look into it

**Comment by flavorjones** [comment]
I've fixed the documentation on how to force-upgrade to the latest version.
