### ISSUE TITLE
Invoking chromedriver-update without a version should always update?

### ISSUE THREAD

**Issue by bobziuchkovski** [flavorjones/chromedriver-helper#47]
I was working with a colleague to update their chromedriver and noticed that `chromedriver-update`, when invoked without a version argument, no-ops if a version of chromedriver is already downloaded.  This seems unintuitive.  I'd expect invoking `chromedriver-update` to fetch the latest version of chromedriver regardless of the currently-installed version.  Is this intentional behavior?  If so, even outputting a message informing the user that no update will be performed unless they remove the current version would be helpful.  Or supporting an override flag to force the upgrade.  Or anything except for exiting silently with no action.  :)

**Comment by flavorjones** [comment]
Yes, I totally agree this is a bug. Fixing right now, will be in the next version.
