### ISSUE TITLE
Add FreeBSD support?

### ISSUE THREAD

**Issue by duncan-bayne** [flavorjones/chromedriver-helper#51]
Currently, chromedriver-helper supports 64-bit and 32-bit Linux, MS Windows, and OSX.

When installed on a FreeBSD system, it breaks Chromedriver by overriding system Chromedriver with a broken .rbenv shim.

Possible fixes include a combination of:

1. Not installing a shim on unsupported systems.
2. Installing a pass-through shim for the system Chromedriver on unsupported systems.
3. Adding support for FreeBSD.

I suspect either (1) or (2) is worthwhile, regardless of whether (3) is implemented.

**Comment by flavorjones** [comment]
I agree that unsupported platforms are something the gem doesn't deal with today, and should. In my imagination, it makes sense for a pass-through shim to be installed that emits a reasonable error message if there is no system Chromedriver installed.

Would you be up for submitting a PR for this?

**Comment by duncan-bayne** [comment]
Yes, absolutely.  If you're interested, I might add FreeBSD support, too? Probably as separate PRs; I think a generic pass-through mechanism is probably more widely useful than FreeBSD support.

**Comment by duncan-bayne** [comment]
And do you think the shim should emit an error message, or try using the system Chromedriver?

I was thinking the latter: perhaps emit a warning, and then look for Chromedriver on $PATH.

**Comment by flavorjones** [comment]
I'd be interested in both PRs. And I agree that I'd like to see the shim emit a warning and then attempt to run the system Chromedriver.

**Comment by flavorjones** [comment]
Closing. Happy to re-open if more conversation is desired.
