### ISSUE TITLE
Chromedriver picks up wrong version

### ISSUE THREAD

**Issue by alexanderadam** [flavorjones/chromedriver-helper#56]
I called `Chromedriver.set_version "2.36"` in spec helper files and also `chromedriver-update 2.36` in terminal.

`ls ~/.chromedriver-helper` shows `2.35  2.36` but when I run the specs I run into this issue:

```
     Selenium::WebDriver::Error::UnknownError:                              
       unknown error: call function result missing 'value'                  
         (Session info: headless chrome=65.0.3325.181)                      
         (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.13.0-38-generic x86_64)
```

The [above issue seems to happen in versions before 2.34](https://github.com/webdriverio/webdriverio/issues/2631) but I don't have this version in `~/.chromedriver-helper`.

So I don't even see where 2.34 might come from so maybe you have an idea regarding this issue?

As this is a desktop system, there is a regular chrome browser running but I also have chromedriver 2.36 explicitely running in another tab:

```bash
$ chromedriver
Starting ChromeDriver 2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752) on port 9515
Only local connections are allowed.
```

Thank you in advance!

**Comment by Mihoid** [comment]
@alexanderadam 
run in terminal 
```chromedriver-update 2.36```
that command will set version 2.36 for chromedriver-helper
after that you can run test normaly :)

**Comment by flavorjones** [comment]
You may also want to delete the `~/.chromedriver-helper` directory, and then run `chromedriver-update 2.36` so that it's the only version installed in your environment.

Can you please let us know if this gets addressed, and if so, how? I'd like to improve the documentation and/or address the usability issue here.

**Comment by alexanderadam** [comment]
@Mihoid as I wrote earlier this didn't help. :wink: 
@flavorjones I did this and chromedriver recreated the `~/.chromedriver-helper/2.36` directory but it fails with the same message.

Is there anything I can do to debug this? Could anything interfere?

**Comment by flavorjones** [comment]
Do you have chromedriver installed somewhere else on your system (e.g., via
a package manager like `apt` or `brew`)?

**Comment by alexanderadam** [comment]
I checked it and I can't see anything.
I'm using Ubuntu and have no chromedriver installed via apt and `brew info chromedriver` returns

```
Error: No available formula with the name "chromedriver" 
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
```

so I guess it's not installed via homebrew either.

![screenshot_20180420_155730](https://user-images.githubusercontent.com/372620/39055369-5a4bdd26-44b4-11e8-88b9-cb13447ab3d8.png)

Any further advice?

**Comment by flavorjones** [comment]
Sorry, I don't have any other ideas. It's clear that you have 2.34 installed somewhere on your system, if I were you I'd focus on locating it to understand how it's getting injected into your project's path.

**Comment by alexanderadam** [comment]
I agree that I seem to have 2.34 somewhere but isn't that a bug if I explicitely set the version with `Chromedriver.set_version` and it isn't picked up?

**Comment by flavorjones** [comment]
I'm not denying it's potentially an issue that we can address -- that's why this Issue is still open. But unless you can help diagnose the issue, or help me reproduce it, I can't really fix anything.

**Comment by flavorjones** [comment]
@mlitwiniuk Thanks for posting, but I'm not sure your response addresses @alexanderadam's issue.

**Comment by alexanderadam** [comment]
That's right. The update is not related to the issue here.
@flavorjones I think I got it. There was also the webdrivers gems installed and it interferred with chromedriver-helper.

So it is fixed now (for me).
But I guess there is something that could be improved regarding the binary finding path. But I don't know how. :wink:

**Comment by flavorjones** [comment]
@alexanderadam can you help me reproduce what you were seeing?
