### ISSUE TITLE
No options to set log log-level and log-path

### ISSUE THREAD

**Issue by thutterer** [flavorjones/chromedriver-helper#59]
Hi :wave: I couldn't find any options to enable and redirect logging for chromedriver.
The chromedriver itself has `--log-level` and `--log-path` command line options.
So for debugging and such, it would be very helpful if there was an easy way to set these options in my spec_helper or environment.

**Comment by flavorjones** [comment]
Thank you for submitting this! I'm just back from vacation and it will take a few days to catch up on everything. Thanks for your patience.

**Comment by thutterer** [comment]
That's okay :relaxed: For now I have a work-around in place that allows me to see logs. 

Just in case anyone else needs this before the gem supports it: I renamed the `chromedriver` executable and in its place I have a simple bash script like this:
```bash
/home/jenkins/.chromedriver-helper/2.41/linux64/chromedriver.bin --log-path=/tmp/chromedriver.log --log-level=SEVERE $@
```

That's pretty ugly but does the job until we have options for logging ... or until I try to update the chromedriver version, which would of course break this hack :wink:

**Comment by n-rodriguez** [comment]
```ruby
    Capybara::Selenium::Driver.new(app,
      browser: :chrome,
      options: options,
      driver_opts: {
        log_path: '/tmp/chrome.log',
        verbose:  true
      }
    )
```

**Comment by flavorjones** [comment]
@thutterer does @n-rodriguez's suggested workaround satisfy your needs? Although I could add a feature to `chromedriver-helper` to pass args through, it might be better to use the features of Capybara::Selenium as the comment suggests.

**Comment by thutterer** [comment]
Yes, that should do it. I'll give it a try next time I touch our CI config!
I just can't find it documented anywhere.
If I had a link to its documentation, I'd add a link to your README ;)

But from my side, this issue can be closed.

**Comment by flavorjones** [comment]
I've documented configuration in 526fbf9. Thanks for prompting this conversation!
