### ISSUE TITLE
Change log directory

### ISSUE THREAD

**Issue by nicholaides** [flavorjones/chromedriver-helper#6]
Is it possible to change the log directory? When used with Rails app, for instance, ./log is great place for log files.

**Comment by flavorjones** [comment]
Hi, I'm terribly sorry for not responding to this -- I just saw it now for the first time, nearly two years later. 

Github notificaiton fail.

In any case, if it's still useful information, you can pass arguments on the command line to chromedriver, and recent versions of chromedriver appear to support a `--log-path=FILE` option.
