### ISSUE TITLE
Chromedriver helper downloading weird chromedriver version number

### ISSUE THREAD

**Issue by summera** [flavorjones/chromedriver-helper#64]
I'm running the [circleci/ruby:2.4.4-node-browsers image](https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/ruby/images/2.4.4-jessie/node-browsers/Dockerfile) on CircleCI and `chromedriver-helper` is pulling a weird version number on install for `chromedriver`.

```ruby
irb(main):012:0> helper = Chromedriver::Helper.new
=> #<Chromedriver::Helper:0x000055f8af5f3ab8>
irb(main):013:0> helper.google_code_parser.newest_download_version.to_s
=> "70.0.3538.16"
```

And when I run `bundle exec chromedriver-helper --version` I get `ChromeDriver 70.0.3538.16 (16ed95b41bb05e565b11fb66ac33c660b721f778)`.

The latest release version of chromedriver is `2.42`. When I go to https://chromedriver.storage.googleapis.com/ I do see some weird version numbers like `70.0.3538.16` which doesn't make much sense. 

```xml
<Contents>
<Key>70.0.3538.16/chromedriver_linux64.zip</Key>
<Generation>1537228578852463</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2018-09-17T23:56:18.852Z</LastModified>
<ETag>"aa7bb2d4a516464162c97ab62d676b88"</ETag>
<Size>3637278</Size>
</Contents>
<Contents>
<Key>70.0.3538.16/chromedriver_mac64.zip</Key>
<Generation>1537228580401426</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2018-09-17T23:56:20.401Z</LastModified>
<ETag>"4d01ffac43d8e63a6bb334dbb99010c0"</ETag>
<Size>5935851</Size>
</Contents>
<Contents>
<Key>70.0.3538.16/chromedriver_win32.zip</Key>
<Generation>1537228581777336</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2018-09-17T23:56:21.776Z</LastModified>
<ETag>"ed2a5a850121af095a61b816319cf42b"</ETag>
<Size>3536229</Size>
</Contents>
```

Since `GoogleCodeParser` is just pulling the max it's going to pull whatever is there. In the [CircleCI docker file](https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/ruby/images/2.4.4-jessie/node-browsers/Dockerfile#L57) they use http://chromedriver.storage.googleapis.com/LATEST_RELEASE to grab the latest release version which does return `2.42`. Maybe that's something that can be done here? 

Initially when I ran into this issue I was getting `Selenium::WebDriver::Error::WebDriverError: unable to connect to chromedriver 127.0.0.1:9515` (unrelated to https://github.com/flavorjones/chromedriver-helper/issues/57 because I had upgraded to chromedriver-helper 2.0.1 already). This may have been due to a temporary issue on Googles end with downloading the zip. Now tests are running just fine but with a weird chromedriver version.

**Comment by swrobel** [comment]
See #62

**Comment by summera** [comment]
@swrobel thanks! Not sure how I missing that. Closing in favor of https://github.com/flavorjones/chromedriver-helper/issues/62
