### ISSUE TITLE
Not executable: chromedriver-helper

### ISSUE THREAD

**Issue by hajarNasr** [flavorjones/chromedriver-helper#70]
I've recently installed Rails on windows 10 and it's working but when I run `rake test` on any project, it gives me this error:

    Selenium::WebDriver::Error::WebDriverError: not executable: "C:/Ruby24- 
    x64/lib/ruby/gems/2.4.0/gems/chromedriver-helper-2.1.0/bin/chromedriver-helper"
    H:/Depot/config/application.rb:7:in `<top (required)>'
    H:/Depot/Rakefile:4:in `require_relative'
    H:/Depot/Rakefile:4:in `<top (required)>'

And I couldn't figure out what might be causing this error. Or reasons why/when chromedriver-helper fails to be executed.

**Comment by flavorjones** [comment]
Hi! Thanks for bringing this up. Windows support is being discussed at #19 , so I'll close this and perhaps you can help us figure out a solution there.
