### ISSUE TITLE
No output with 'which chromedriver' after installing 2.1.0

### ISSUE THREAD

**Issue by philipfong** [flavorjones/chromedriver-helper#72]
Upon installing the latest `chromedriver-helper` via bundler, running `rspec` produces the error "Unable to find chromedriver."

The command `which chromedriver` produces no output from my terminal.

If I were to set my Gemfile to use 1.2.0, `which chromedriver` produces `/Users/pfong/.rvm/gems/ruby-2.5.1/bin/chromedriver`

Any ideas on what might be preventing me from using chromedriver through the latest version of this gem?

**Comment by twalpole** [comment]
chromedriver-helper 2+ changed the name of the binary downloaded because it caused issues for people who had some projects using `chromedriver-helper` and some not -- You can read more about it in the README

**Comment by twalpole** [comment]
and you need to make sure you've required the gem - see https://github.com/flavorjones/chromedriver-helper/pull/67

**Comment by philipfong** [comment]
Thanks! Adding `require chromedriver-helper` seemed to do the trick.
