### ISSUE TITLE
Version selection with LATEST_RELEASE is deprecated

### ISSUE THREAD

**Issue by starsirius** [flavorjones/chromedriver-helper#79]
We've been getting `chrome not reachable` errors in our CircleCI builds since Chrome 73 was released. It seemed like chromedriver-helper was still installing Chromedriver 2.46 as the error message showed

```
Selenium::WebDriver::Error::WebDriverError:
  chrome not reachable
    (Session info: headless chrome=73.0.3683.75)
    (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.10.0-35-generic x86_64)
```

Currently chromedriver-helper fetches the latest chromedriver version via [https://chromedriver.storage.googleapis.com/LATEST_RELEASE](https://github.com/flavorjones/chromedriver-helper/blob/v2.1.0/lib/chromedriver/helper/google_code_parser.rb#L15). It's now deprecated as in the [thread](https://groups.google.com/forum/#!topic/chromedriver-users/8VmMaFjs1cg), and we should switch to the new way of [version selection](https://sites.google.com/a/chromium.org/chromedriver/downloads/version-selection).

We are testing if updating to the matching version manually will resolve the issue for the time being:
```
chromedriver-update 73.0.3683.68
```

**Comment by nshki** [comment]
@starsirius We've been getting the same error as of today. Please keep us posted, I'll be watching this issue.

**Comment by ioquatix** [comment]
Our specs have started to fail too:

```
      Selenium::WebDriver::Error::SessionNotCreatedError:
        session not created: This version of ChromeDriver only supports Chrome version 74
          (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-1026-gcp x86_64)
```

**Comment by starsirius** [comment]
Updating Chromedriver to 73.0.3683.68 didn't resolve the issue. Still getting the same error. Looks like people have [reported](https://groups.google.com/forum/#!topic/chromedriver-users/ZBEju24L5ww) similar incompatibility issue.

```
Selenium::WebDriver::Error::WebDriverError:
  chrome not reachable
    (Session info: headless chrome=73.0.3683.75)
    (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.10.0-35-generic x86_64)
```

**Comment by ioquatix** [comment]
We temporarily worked around this issue by manually installing the right version:

## In `.travis.yaml`

```yaml
before_script:
  - bundle exec chromedriver-update 2.46
```

**Comment by kichion** [comment]
Our specs have started to fail. An example of a solution with CircleCI is
```yml
    - run:
        name: Install Fixed Version ChromeDriver
        command: |
          rm -rf $HOME/.chromedriver-helper
          bundle exec chromedriver-update 73.0.3683.68
```

**Comment by moro** [comment]
Hi. (This is an off-topic from the issue title, but may help someone.)

We got similar test failure on our tests and found a solution for us.

We have `options.add_argument('--disable-dev-shm-usage')` option in our spec helper once we set up our system spec, which runs on Docker on CircleCI.

Then I found 
https://github.com/SeleniumHQ/docker-selenium#running-the-images today
> This is a known workaround to avoid the browser crashing inside a docker container, here are the documented issues for Chrome and Firefox. 

So I dropped the option, then our tests success 🎉 
If your config has same option, try it on.

Thanks.

**Comment by longwave** [comment]
Thanks to the above posters I am now using the following script to detect the version of Chrome and install the correct version of Chromedriver, this should follow the official version selection algorithm:

```
CHROME_VERSION=$(google-chrome --version | sed -r 's/[^0-9]+([0-9]+\.[0-9]\.[0-9]+).*/\1/g')
CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
bundle exec chromedriver-update $CHROMEDRIVER_VERSION
```

**Comment by nshki** [comment]
@moro This fixed the issue for us as well, thanks so much!

**Comment by michaelcarter** [comment]
On Codeship, I was getting a `This version of ChromeDriver only supports Chrome version 74` error, fixed for me by adding the following to my build steps:

```
export CHROMEDRIVER_VERSION=73.0.3683.68
\curl -sSL https://raw.githubusercontent.com/codeship/scripts/master/packages/chromedriver.sh | bash -s
bundle exec chromedriver-update $CHROMEDRIVER_VERSION
```

**Comment by seanlinsley** [comment]
Here's a version that works both on Ubuntu and MacOS: https://gist.github.com/seanlinsley/36a204862f08942b0667e941331f3a75

I would open a PR for this gem, but it's not clear to me why `GoogleCodeParser` is using `Gem::Version` for comparisons. Is there some extra history to this logic?
https://github.com/flavorjones/chromedriver-helper/blob/5508af7ff3b955d4417baa2ebd882c510d190c1c/lib/chromedriver/helper/google_code_parser.rb#L25-L27
https://github.com/flavorjones/chromedriver-helper/blob/5508af7ff3b955d4417baa2ebd882c510d190c1c/lib/chromedriver/helper/google_code_parser.rb#L36-L38

There's also the question of whether `downloads` (which does XML parsing) is still needed, or if it could rely on the `LATEST_RELEASE_#{version}` API instead.

**Comment by connorshea** [comment]
@seanlinsley do you have a fork we can use to test this with?

**Comment by seanlinsley** [comment]
I don't have a fork at the moment, but you can copy that code into your project to test (I put it in `spec/support/chromedriver.rb`)

**Comment by flavorjones** [comment]
A PR would be very welcome here, I don't know that I'll have the opportunity to look into this before the weekend.

**Comment by flavorjones** [comment]
@seanlinsley you asked

> I would open a PR for this gem, but it's not clear to me why `GoogleCodeParser` is using `Gem::Version` for comparisons. Is there some extra history to this logic?

Yes, `Gem::Version` is an object that implements `#<=>` to sort version strings as you'd expect (as opposed to lexicographical sort), so we can, for example, call `#max` on an Array and get the latest version. So it seems like it's not needed in your [gist](https://gist.github.com/seanlinsley/36a204862f08942b0667e941331f3a75).

**Comment by flavorjones** [comment]
I'd also like to point everyone at #78 in which I point out some risks around an implementation like the one suggested by @seanlinsley, mainly, that the name and location of the chrome/chromium binary may not be obvious to find and may therefore be problematic in and of itself.

**Comment by bransynluther** [comment]
> We temporarily worked around this issue by manually installing the right version:
> 
> ## In `.travis.yaml`
> ```yaml
> before_script:
>   - bundle exec chromedriver-update 2.46
> ```

We are using codeship to run our builds, and this answer fixed our problem for Ruby on Rails.
ioquatix, thank you.

**Comment by flavorjones** [comment]
I'm going to close this issue, as the gem is being deprecated in favor of webdrivers, see #83.
