### ISSUE TITLE
Seeking new maintainer

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/chromedriver-helper#80]
Hi there,

I have not coded in Rails or used chromedriver in quite some time, and so I'm pretty far from the day-to-day needs of most users of chromedriver-helper. To be honest, there are some design decisions that need to be made, and work that needs to be done; and I don't have the well-formed opinions or the motivation that a daily user of the gem might have.

So I'm seeking someone to help maintain this gem; or even take it over entirely. Please comment on this github issue if you're interested!

Some things that need doing:

* we need to make a decision about how the gem should determine what version of chromedriver to download (#78, #79)
* window support is apparently not working as well as it once did and there's no clear solution (#19)

Thanks for reading.

**Comment by connorshea** [comment]
@flavorjones thanks for your work on this gem :heart: 

It may be worth posting this on the Ruby on Rails core team mailing list, since this gem is a default dependency of Rails.

**Comment by flavorjones** [comment]
@connorshea Thanks for the note. I've reached out to a Rails Core team member to ask if they can help.

**Comment by kapoorlakshya** [comment]
Hi @flavorjones, I'm interested in being a maintainer for this gem. I recently submitted a PR to the `webdrivers` gem that solves #78 and #79 there - https://github.com/titusfortner/webdrivers/pull/32

**Comment by flavorjones** [comment]
Hi @kapoorlakshya, thanks so much for responding!

Since you seem to be pretty familiar with the `webdrivers` gem, let me ask: should I just stop maintaining this gem and ask everyone to use `webdrivers` instead?

**Comment by kapoorlakshya** [comment]
@flavorjones That is a good option to be honest. I almost suggested that in my previous comment 🙂.

I see two benefits in using the `weberivers` gem:
1. Support for all major browsers.
2. The gem is maintained by Titus Fortner who is an active contributor to the [Watir](https://github.com/watir/watir) and `selenium-webdriver` projects. This means the gem will most likely get long term support from him.

**Comment by borama** [comment]
@flavorjones @kapoorlakshya Just a note: the `webdrivers` gem is fine but we recently migrated from it to `chromedriver-helper` because I didn't like that it checks for a new version (parsing a several hundred kBs network response) *each* time a new test session starts - a behavior which can't be disabled in the configuration (titusfortner/webdrivers#29). 

Personally, I much prefer the semi-manual upgrades (and chromedriver stability in between them) that this gem provides. :heart:

**Comment by kapoorlakshya** [comment]
@borama You raise a valid concern and that is a drawback of using that gem over this one. We will definitely have to port some features over to `webdrivers` to make the transition as smooth as possible. Especially since this gem is included in `rails`.

For now, I'm willing to update this gem with a solution for #78 and #79 (if @flavorjones approves). In the near future, we can consider the possibility of switching over to `webdrivers` once we have we implemented a solution for https://github.com/titusfortner/webdrivers/issues/29.

**Comment by titusfortner** [comment]
Fwiw, the reasoning for the webdrivers implementation is that most local browsers automatically update. Likely the most common problem people bring up in the Selenium forums has had to do with outdated drivers after a browser update.

I haven't done a thorough comparison between these projects, so feel free to raise issues on webdrivers if there is something that is missing. @twalpole you've used both, anything glaringly different?

@kapoorlakshya you're also welcome to be added as a maintainer on webdrivers, obviously I haven't gotten a chance to review your PR yet. 

I personally prefer having one project for all the drivers which is how other languages seem to be doing it as well.

**Comment by borama** [comment]
I see. In my local system (Arch Linux), Chrome does not auto update, but that's not an issue for me. Browser version stability and controlled upgrades are more important to us in our CI environment where we run the automatic tests. I am not sure I would like _anything_ to be automatically upgraded there as I want to prevent tests failing in unexpected ways.

I definitely understand the trend to unify these gems to the `webdrivers` project and can try to help with issues etc. there. Thank you all!

**Comment by titusfortner** [comment]
Webdrivers gem currently lets you specify a specific driver version which short cuts the need for a network call.

**Comment by titusfortner** [comment]
Ok, I did a review of the webdrivers code, it... needs a little bit of tidying. I made a list of the things that we need to get straightened out to provide the functionality people have asked for: https://github.com/titusfortner/webdrivers/issues. They should be relatively straightforward to fix.

Let me know if there is anything else missing, and we'll add it, then release a 4.0 version to make it easy to differentiate the updated functionality / API.

Thanks!

**Comment by kapoorlakshya** [comment]
I just released a new version (v3.7.0) of `webdrivers` gem - it fetches the correct `chromedriver` version for the installed version of Chrome. For example, if you have Chrome 73.0.3683.75 installed, it will default to downloading the latest build of `chromedriver` 73.0.3683.xx.

And as @titusfortner mentioned earlier, you can use `Webdrivers::Chromedriver.version = '73.0.3683.68'` (or whichever version you desire) to limit the network calls from 12 to 4.

**Comment by odlp** [comment]
@flavorjones as a long-time `chromdriver-helper` user I'd be happy to help maintain the gem!

**Comment by flavorjones** [comment]
HI all, thanks for the amazing conversation and rallying around the idea of deprecating this gem in favor of `webdrivers`.

@kapoorlakshya Thanks for the offer of addressing #78 and #79 in this gem; however, a wise person once told me to "never waste a crisis" and so I'm inclined to use this as an opportunity to convince people to migrate to `webdrivers` in order to have this issue addressed.

I'm going to open a new issue, and will link to it from here, to give public notice that I'm winding down support for this gem, and have a punch list that reflects the set of activities required to wind it down responsibly.

Please let me know if you think this is a terrible idea, I'm happy to discuss it. But I'm pretty convinced it's the right thing to do.

**Comment by flavorjones** [comment]
That notice has been published under #83.

**Comment by kapoorlakshya** [comment]
Thank you for all your work on this gem, @flavorjones. I've begun updating `webdrivers` to ensure a smooth transition for the users. Take care!
