### ISSUE TITLE
Doc question

### ISSUE THREAD

**Issue by justin808** [flavorjones/chromedriver-helper#82]
```
If you want to run a specific version of chromedriver in your project, you can set the version in you testing setup like so:

Chromedriver.set_version "2.24"
```

Where is the `in you testing setup`? per the README.

**Comment by flavorjones** [comment]
Justin, you should be able to set this, e.g. in your `spec_helper.rb` file. Pretty much anywhere your tests are bootstrapping. Hope this helps!
