### ISSUE TITLE
NOTICE: Ending support for this gem

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/chromedriver-helper#83]
Ahoy, Rubyists.

This issue, related to #80 (and through that, to #78 and #79), intends to:

1. Give public notice of ending support for `chromedriver-helper`, and deprecating it in favor of the [`webdrivers`](https://github.com/titusfortner/webdrivers) gem which has very nearly a superset of the functionality.
2. Provide a punch list to track what needs to be done to wind down this gem responsibly, and provide transparency into the state of support/deprecation.

More to follow.

**Comment by flavorjones** [comment]
__Rationale__

1. I have not coded in Rails or used chromedriver in quite some time, and so I'm pretty far from the day-to-day needs of most users of chromedriver-helper. To be honest, there are some design decisions that need to be made, and work that needs to be done; and I don't have the well-formed opinions or the motivation that a daily user of the gem might have.
2. The [`webdrivers`](https://github.com/titusfortner/webdrivers) gem is well-maintained, is very nearly a superset of the functionality of this gem (and supports all major webdrivers), and further has maintainers interested in providing what little this gem does that's not already provided.
3. There's value to the community in having one well-supported and well-maintained gem that handles a given concern; and IMHO there is little-to-nothing to innovate on in this space.

**Comment by flavorjones** [comment]
__Punchlist__

Things I think need to be done in order to complete deprecation, ideally by __2019-03-31__:

- [x] send an announcement email to ruby-talk@
- [x] notify maintainers of the `webdrivers` gem (/cc @titusfortner)
- [x] notify rails-core contributors, as it's the largest reverse-dependency on this gem in the form of generate `rails new` projects
- [x] update the README, CHANGELOG, and other project metadata
- [x] release a patch version (likely `v2.1.1`) of the gem with a `post-install message` indicating that the gem is deprecated and out of support, and pointing users to `webdrivers`
- [x] archive the git repository
- [x] turn off CI at https://ci.nokogiri.org/teams/flavorjones/pipelines/chromedriver-helper and https://ci.nokogiri.org/teams/flavorjones/pipelines/chromedriver-helper-pr
- [x] celebrate the gem's success and relax with a beer

**Comment by flavorjones** [comment]
ruby-talk notification is at http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/440018

**Comment by flavorjones** [comment]
v2.1.1 has been shipped with a post-install-message deprecation notice, and updated gemspec summary and description.

**Comment by connorshea** [comment]
@flavorjones you should include a message in the Changelog as well.

**Comment by guilleiguaran** [comment]
Changed in Rails, new Rails 6.0.0 apps will ship `webdrivers` instead of `chromedriver-helper`

**Comment by pixeltrix** [comment]
@guilleiguaran should we also backport that to 5-2-stable as well?

**Comment by nodanaonlyzuul** [comment]
Thanks @flavorjones (and everyone else who has contributed) - enjoy that well earned, final punch-list item.

**Comment by ioquatix** [comment]
Thanks for being an awesome maintainer.

**Comment by EverybodyKurts** [comment]
Just wanted to say thank you for this gem and the good work you did. This gem helped me run integration tests in chrome and I didn't have to do a lot of setup or config. Great job.

**Comment by lazlyhu** [comment]
Huge respect because the just released `post-install-message`! 🏅

**Comment by hybridspyda** [comment]
Trying to upgrade to using the webdrivers gem instead, running into issues:

	Selenium::WebDriver::Error::UnknownError:
	unknown error: Chrome failed to start: crashed
	 (unknown error: DevToolsActivePort file doesn't exist)
	 (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
	 (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.4.0-17763-Microsoft x86_64)

My driver was previously setup and working using the following config:

	require 'selenium-webdriver'
	Capybara.register_driver :headless_chrome do |app|
		capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
			chromeOptions: { args: %w[headless disable-gpu] } # extras: no-sandbox disable-extensions
		)

		Capybara::Selenium::Driver.new(
			app,
			browser: :chrome,
			desired_capabilities: capabilities
		)
	end
	Capybara.javascript_driver = :headless_chrome
	Capybara.current_driver = :headless_chrome

Thanks in advance!

**Comment by flavorjones** [comment]
@hybridspyda Please open an issue with the webdrivers gem.

**Comment by flavorjones** [comment]
CI pipelines have been deleted from https://ci.nokogiri.org/.

I'm about to archive this git repo, and so I'll ask you all to trust that this evening I will kick back with a beer as required in the punchlist above.

![lando-wave](https://user-images.githubusercontent.com/8207/55324771-100ecb80-5451-11e9-91fc-a5d4d8f13b63.gif)
